# permissions for end users to edit updateconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: updateconfig-editor-role
rules:
- apiGroups:
  - customapp.prasad.com
  resources:
  - updateconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - customapp.prasad.com
  resources:
  - updateconfigs/status
  verbs:
  - get
